<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'DEBUG' => 'false',
  'APP_SECRET' => 'app-secret',
  'APP_DB_DIR' => 'syncthing/Sync',
  'APP_KDBX_FILENAME' => 'syncthing/Sync/test4.kdbx',
  'APP_KDBX_KEYFILE' => 'syncthing/Sync/test4.key',
  'APP_KDBX_PASSWORD' => 'password',
  'APP_KDBX_TIMEOUT' => '5',
  'HTTP_BASIC_AUTH_USERNAME' => 'user',
  'HTTP_BASIC_AUTH_PASSWORD' => 'pass',
);
